version: 1.0.{build}
before_build:
- ps: >-
    choco install -y mingw -x86

    ls "C:/tools"
    
    ls "C:/tools/mingw32"
    
    ls "C:/tools/mingw32/bin"
    
    Write-Host "    Downloading pexports..."
    
    curl -o "pexports.tar.xz" "https://github.com/callofduty4x/CoD4x_Server/raw/master/tools/pexports-0.47-mingw32-bin.tar.xz"
    
    Write-Host "    Installing pexports..."

    7z x pexports.tar.xz | Out-Null

    7z x pexports.tar | Out-Null

    Write-Host "Setting up NASM:"
    
    Write-Host "    Downloading NASM..."
    
    curl -o nasminst.exe http://libgd.blob.core.windows.net/nasm/nasm-2.07-installer.exe
    
    Write-Host "    Installing NASM..."
    
    .\nasminst.exe /S
    
    Write-Host "Setting up environment variables."
    
    [Environment]::SetEnvironmentVariable("PATH",  "C:\tools\mingw32\bin;$pwd\bin;C:\Program Files (x86)\nasm;$($env:path)")

build_script:
- ps: >-
    Write-Host "Building server code:"

    Write-Host "    Building tomcrypt..."

    cd src/tomcrypt

    ./compile_win32.cmd | Out-Null

    Write-Host "    Building mbedtls..."

    cd ../mbedtls

    ./build.cmd  | Out-Null
    
    Write-Host "    Building cod4x18 server..."

    cd ../..

    mingw32-make.exe win32

    Write-Host "Done."
test_script:
- ps: ./bin/cod4x18_dedrun.exe
branches:
  only:
    - master    # Ignore all other branches.
artifacts: 
  - path: bin\cod4x18_dedrun.exe
    name: cod4exe
deploy:
- provider: GitHub
  auth_token:
    secure: Je7YohhSVawAyVkWQG3zyoppIB73CjJB99IlzzJzosFJ5NeBkYLUuA2SV52LTWXj
  artifact: cod4exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
